### ISSUE TITLE
Build broken on GCC 6.3

### ISSUE THREAD

**Issue by Ozaq** [IOT-DSA/sdk-dslink-c#16]
Calling ./build from tools results in the following error on Ubuntu 17.04 with GCC 6.3:

```
Scanning dependencies of target sdk_dslink_c-object
[ 22%] Building C object CMakeFiles/sdk_dslink_c-object.dir/deps/argtable3/src/argtable3.c.o
/data/sdk-dslink-c/deps/argtable3/src/argtable3.c: In function ‘trex_compile’:
/data/sdk-dslink-c/deps/argtable3/src/argtable3.c:3480:11: error: variable ‘tmp’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
     TRex *tmp = exp;
           ^~~
cc1: all warnings being treated as errors
CMakeFiles/sdk_dslink_c-object.dir/build.make:62: recipe for target 'CMakeFiles/sdk_dslink_c-object.dir/deps/argtable3/src/argtable3.c.o' failed
make[2]: *** [CMakeFiles/sdk_dslink_c-object.dir/deps/argtable3/src/argtable3.c.o] Error 1
CMakeFiles/Makefile2:258: recipe for target 'CMakeFiles/sdk_dslink_c-object.dir/all' failed
make[1]: *** [CMakeFiles/sdk_dslink_c-object.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Pacane** [comment]
I had this issue as well when trying to build it a while back.


The solution was this for me:

> let's change the cmake command for debug:
```cmake -DDSLINK_BUILD_BROKER=ON  -DCMAKE_BUILD_TYPE=Debug ..```

cc: @akarademir

**Comment by akawamura** [comment]
List of all errors/warnings which came from third-party software:

sdk-dslink-c/deps/jansson/src/lookup3.h:362:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
sdk-dslink-c/deps/jansson/src/lookup3.h:363:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
sdk-dslink-c/deps/jansson/src/lookup3.h:364:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
sdk-dslink-c/deps/jansson/src/lookup3.h:365:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
sdk-dslink-c/deps/jansson/src/lookup3.h:366:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
sdk-dslink-c/deps/jansson/src/lookup3.h:367:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
sdk-dslink-c/deps/jansson/src/lookup3.h:368:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
sdk-dslink-c/deps/jansson/src/lookup3.h:369:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
sdk-dslink-c/deps/jansson/src/lookup3.h:370:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
sdk-dslink-c/deps/jansson/src/lookup3.h:371:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
sdk-dslink-c/deps/jansson/src/lookup3.h:372:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
sdk-dslink-c/deps/argtable3/argtable3.c:3070:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
sdk-dslink-c/deps/argtable3/argtable3.c:3467:8: warning: variable ~exp~ might be clobbered by ~longjmp~ or ~vfork~ [-Wclobbered]
sdk-dslink-c/deps/mbedtls/library/x509_crl.c:508:5: warning: this ~else~ clause does not guard... [-Wmisleading-indentation]
sdk-dslink-c/deps/mbedtls/library/x509_crt.c:1173:62: warning: ~%s~ directive output may be truncated writing up to 255 bytes into a region of size 254 [-Wformat-truncation=]
sdk-dslink-c/deps/argtable3/argtable3.c:3070:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
sdk-dslink-c/deps/argtable3/argtable3.c:3467:8: warning: variable ~exp~ might be clobbered by ~longjmp~ or ~vfork~ [-Wclobbered]
sdk-dslink-c/deps/mbedtls/library/x509_crl.c:508:5: warning: this ~else~ clause does not guard... [-Wmisleading-indentation]
sdk-dslink-c/deps/mbedtls/library/x509_crt.c:1173:62: warning: ~%s~ directive output may be truncated writing up to 255 bytes into a region of size 254 [-Wformat-truncation=]

======
Disable those by adding the following to the top CMakeLists.txt

if (NOT NO_WARNINGS)
    ADD_C_FLAGS("-Wall -Wextra -Werror")
    ADD_C_FLAGS("-Wno-overlength-strings")
    **ADD_C_FLAGS("-Wno-implicit-fallthrough")
    ADD_C_FLAGS("-Wno-clobbered")
    ADD_C_FLAGS("-Wno-misleading-indentation")
    ADD_C_FLAGS("-Wno-format-truncation")**
    ADD_C_FLAGS("-pedantic")
endif()
