### ISSUE TITLE
Consider this patch

### ISSUE THREAD

**Issue by savinirsch** [IOT-DSA/sdk-dslink-c#17]
Below patch helps in 

- DSLink stop taking a lot of time,  due to not flushing the messages.
- DSLink SDK should ack the req/response reception before processing the same.

Please review and commit the same.

**Comment by savinirsch** [comment]
[patch.txt](https://github.com/IOT-DSA/sdk-dslink-c/files/1007483/patch.txt)

**Comment by akawamura** [comment]
- Incorporated first patch into dslink_close function.

**Comment by savinirsch** [comment]
thanks
