### ISSUE TITLE
build failure on ubuntu

### ISSUE THREAD

**Issue by savinirsch** [IOT-DSA/sdk-dslink-c#18]
Scanning dependencies of target storage
[ 71%] Building C object CMakeFiles/storage.dir/examples/storage/src/main.c.o
[ 72%] Linking C executable storage

libjansson.a(value.c.o): In function `json_binary_nocheck':
value.c:(.text+0x9db): undefined reference to `dslink_base64_url_encode'
libjansson.a(value.c.o): In function `json_binaryn_nocheck':
value.c:(.text+0xac3): undefined reference to `dslink_base64_url_encode'
libjansson.a(value.c.o): In function `json_binary_value':
value.c:(.text+0xcd2): undefined reference to `dslink_base64_url_decode'
collect2: error: ld returned 1 exit status
make[2]: *** [storage] Error 1
make[1]: *** [CMakeFiles/storage.dir/all] Error 2
make: *** [all] Error 2

**Comment by akarademir** [comment]
fixed
