### ISSUE TITLE
Regarding Deployment of DSLink in C broker

### ISSUE THREAD

**Issue by pra0909** [IOT-DSA/sdk-dslink-c#23]
Hi team, 
I want to deploy a dslink on c-broker. but i am only able to deploy a dslink via ide only. is there any way to deploy dslink on c-broker.

**Comment by logangorence** [comment]
I'm confused as to what problem you are having here. You can build both your DSLink and the C Broker using CMake, you can use tools/build.sh to build it, or use the usual commands for a CMake project:
```
mkdir build
cd build
cmake ..
make
```

**Comment by pra0909** [comment]
Thanks for your response, Actually i want to deploy Alarm java dslink on c broker but i am not able to do it.
So can you please suggest how can i achieve it ??

**Comment by logangorence** [comment]
To do this without a DGLux Server (which has the ability to manage DSLinks), you'll either need to build the DSLink from source, or you can download prebuilt versions from the zip field in [this file](https://github.com/IOT-DSA/links/blob/gh-pages/links.json), as far as I know, we don't have a user interface for downloading only links, but building them into the DGLux Server ZIP. The URL for the specific DSLink you want is the following: https://dsa.s3.amazonaws.com/links/files/dslink-java-alarm.zip

Additionally, if you want to run this at system startup, on Linux/macOS you'll need to add some sort of init script/service file (depends on the distro), and on Windows, you could create a service, but I don't have much knowledge of doing that.

**Comment by mbreissi** [comment]
Alternatively, you could use the Cisco EFM version of the C Broker, which includes lifecycle management services equivalent to the DGLux Server.  Like DGLux Server, however, that version is not open source/free.
