### ISSUE TITLE
Test the exmaple code failed.

### ISSUE THREAD

**Issue by eciot** [IOT-DSA/sdk-dslink-c#26]
When I execute "requester", it will be blocked forever.

I found  sem_wait is called before sem_init(ws_queue_sem).

The issue code is ws.c (line:430), just sem_init(ws_queue_sem) before call on_requester_ready_cb:

  if (on_requester_ready_cb) {
        on_requester_ready_cb(link);
    }

#ifdef DSLINK_WS_SEND_THREADED
    link->closingSendThread = 0;
    uv_sem_init(&link->ws_send_sem,0);
    uv_sem_init(&link->ws_queue_sem,1);
    uv_thread_t send_ws_thread_id;
    uv_thread_create(&send_ws_thread_id, dslink_send_ws_thread, link);
#endif

**Comment by akawamura** [comment]
This has been addressed in https://github.com/IOT-DSA/sdk-dslink-c/pull/20 and
https://github.com/IOT-DSA/sdk-dslink-c/pull/27
